config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, :origins, :origin_fields, :processids, :tables, :campaigns, :variables


  post "index" => "welcome#index"
  get  "index" => "welcome#index"

  post "/create_or_update_origin_field" => "origins#create_or_update_origin_field"
  get "/get_origin_field_to_update"     => "origins#get_origin_field_to_update"
  delete "/destroy_origin_field"        => "origins#destroy_origin_field"

  post "/create_origin_field_upload" => "origins#create_origin_field_upload"

  match '/export_script', to: 'scripts#index', via: [:get, :post]

  match 'variable_name_search'               , to: 'variables#name_search'          , :via => :get
  match 'campaign_variables_search/(:id)'    , to: 'campaigns#variables_search'     , :via => :get
  match 'table_variables_search/(:id)'       , to: 'tables#variables_search'        , :via => :get
  match 'processid_variables_search/(:id)'   , to: 'processids#variables_search'    , :via => :get
  match 'origin_field_name_search'           , to: 'origins#name_search'            , :via => :get
  match 'variable_origin_fields_search/(:id)', to: 'variables#origin_fields_search' , :via => :get

  get "user/index"
  get "/login"             => "users#login"
  post "/signin"           => "users#authenticate"
  get  "/signup"           => "users#new"
  get  "/logout"           => "users#logout"
  get  "/password"         => "users#password"
  post "/password_update"  => "users#password_update"

  get  "/remember_password/:id" => "users#remember_password_index", :as => "remember"
  post "/remember_password"     => "users#remember_password"

  get "/search/origin"    => "origins#search",    :as => "search_origin"
  get "/search/campaign"  => "campaigns#search",  :as => "search_campaign"
  get "/search/table"     => "tables#search",     :as => "search_table"
  get "/search/processid" => "processids#search", :as => "search_processid"
  get "/search/variable"  => "variables#search",  :as => "search_variable"
end

app/models/origin.rb
class Origin < ActiveRecord::Base
  include UserSession

  before_save :calculate_hive_table_name
  before_save :calculate_cd5_portal_destination_name
  before_save :calculate_cd5_portal_origin_name

  has_many :origin_fields

  scope :draft,       -> { where(status: Constants::STATUS[:SALA1]) }
  scope :development, -> { where(status: Constants::STATUS[:SALA2]) }
  scope :done,        -> { where(status: Constants::STATUS[:PRODUCAO]) }

  scope :recent,      -> { order(updated_at: :desc) }

  # room1 validations
  validates :file_name,                   presence: true, length: { maximum: 50 }, if: :current_user_is_room1?
  validates :file_description,            presence: true, length: { maximum: 200 }, if: :current_user_is_room1?
  validates :created_in_sprint,           presence: true, if: :current_user_is_room1?
  validates :updated_in_sprint,           presence: true, if: :current_user_is_room1?
  validates :abbreviation,                presence: true, length: { maximum: 3 }, if: :current_user_is_room1?
  validates :base_type,                   presence: true, if: :current_user_is_room1?
  validates :book_mainframe,              length: { maximum: 10 }, if: :current_user_is_room1?
  validates :periodicity,                 presence: true, if: :current_user_is_room1?
  validates :periodicity_details,         length: { maximum: 50 }, if: :current_user_is_room1?
  validates :data_retention_type,         presence: true, if: :current_user_is_room1?
  validates :dmt_advice,                  length: { maximum: 200 }, if: :current_user_is_room1?
  validates :dmt_classification,          presence: true, if: :current_user_is_room1?
  validates :extractor_file_type,         presence: true, if: :current_user_is_room1?
  validates :room_1_notes,                length: { maximum: 500 }, if: :current_user_is_room1?
  validates :dmt_advice,                  length: { maximum: 200 }, if: :current_user_is_room1?
  validates :dmt_classification,          presence: true, if: :current_user_is_room1?
  validates :status,                      presence: true

  # room2 validations
  validates :mnemonic,                    uniqueness: true, presence: true, length: { maximum: 4 }, if: :current_user_is_room2?
  validates :cd5_portal_origin_code,      uniqueness: true, presence: true, if: :current_user_is_room2?
  validates :cd5_portal_destination_code, uniqueness: true, presence: true, if: :current_user_is_room2?
  validates :mainframe_storage_type,      presence: true, if: :current_user_is_room2?
  validates :room_2_notes,                length: { maximum: 500 }, if: :current_user_is_room2?

  def code
    "OR#{self.id.to_s.rjust(3,'0')}"
  end

  def status_screen_name
    file_name[0..19] if file_name?
  end

  private

  def calculate_hive_table_name
    self.hive_table_name = self.mnemonic? ? "ORG_#{self.mnemonic}".upcase : nil
  end

  def calculate_cd5_portal_destination_name
    self.cd5_portal_destination_name = self.mnemonic? ? "CD5.RETR.B#{self.mnemonic}".upcase : nil
  end

  def calculate_cd5_portal_origin_name
    self.cd5_portal_origin_name = self.mnemonic? ? "CD5.BASE.O#{self.mnemonic}".upcase : self.cd5_portal_origin_name = nil
  end
end

app/controllers/origins_controller.rb
class OriginsController < ApplicationController
  before_action :set_origin,      only: [:show, :edit, :update]
  before_action :set_query_param, only: [:search]
  before_filter :ensure_authentication

  def name_search
    if params[:term].present?
      @origin_fields = OriginField.where( "origin_fields.origin_file_field_name like ?", "%#{params[:term]}%" )
    else
      @origin_fields = OriginField.all
    end
    render json: @origin_fields
  end

  def index
    @origins = Origin.all.paginate(page: params[:page], per_page: 10)
  end

  def search
    @origins = Origin.where(@text_param).where(@status_param).paginate(page: params[:page], per_page: 10).to_a

    render :index
  end

  def show
    @origin_field = OriginField.new
  end

  def new
    @origin = Origin.new
  end

  def edit
  end

  def create
    @origin = Origin.new(origin_params.merge(status: Constants::STATUS[:SALA1]))

    respond_to do |format|
      if @origin.save
        format.html { redirect_to @origin, notice: "#{Origin.model_name.human.capitalize} criado com sucesso" }
        format.json { render :show, status: :created, location: @origin }
      else
        format.html { render :new }
        format.json { render json: @origin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    old_status = @origin.status
    status = params[:update_status] ? { status: params[:update_status] } : {}

    respond_to do |format|
      if @origin.update(origin_params.merge(status))
        format.html { redirect_to @origin, notice: "#{Origin.model_name.human.capitalize} atualizado com sucesso" }
        format.json { render :show, status: :ok, location: @origin }
      else
        @origin.status = old_status
        format.html { render :edit }
        format.json { render json: @origin.errors, status: :unprocessable_entity }
      end
    end
    set_desabled_fields
  end

  def create_or_update_origin_field
    @origin         = Origin.find(params[:origin_field][:origin_id])
    origin_field_id = params[:origin_field][:origin_field_id]
    if origin_field_id.blank?
      @origin_field = OriginField.new(origin_field_params)
    else
      if ( @origin_field = OriginField.find(origin_field_id) )
        @origin_field.update(origin_field_params.merge!( :id => origin_field_id ))
      end
    end
    if @origin_field.save
      redirect_to @origin, notice: "#{OriginField.model_name.human.capitalize} criado com sucesso"
    else
      render :show
    end
  end

  def destroy_origin_field
    origin_field_id = params[:format]
    unless origin_field_id.empty?
      if ( @origin_field = OriginField.find(origin_field_id) )
        @origin          = Origin.find(@origin_field.origin_id)
        if @origin_field.destroy
          redirect_to @origin, notice: "#{OriginField.model_name.human.capitalize} excluido com sucesso"
        else
          render :new
        end
      end
    end
  end

  def get_origin_field_to_update
    @origin_field = OriginField.find(params[:id])
    @origin       = Origin.find(@origin_field.origin_id)
    set_desabled_fields
    render :show
  end

  def create_origin_field_upload
    @data_file = params[:origin_field][:datafile]
    @origin = Origin.find(params[:origin_field][:origin_id])
    unless @data_file
      redirect_to @origin, notice: "Voce tentou fazer Upload sem selecionar um arquivo. Selecione um arquivo, por favor."
    else
      @file_type = params[:file_type]

      array_linha = Array.new
      conta_linha = 0
      conta_valido = 0

      resultado = false

      # abre o arquivo temporario
      File.open(@data_file.tempfile) do |txt|
        txt.each_line() do |linha|

          # ignora o header e linhas vazias para oa arquivos do hadoop
          array_linha = linha.split(",")
          if @file_type == "hadoop" && array_linha.size > 1 && conta_linha > 0
            resultado = OriginField.text_parser(@file_type, linha, @origin.id, current_user.id)
            conta_valido += 1
          elsif (!linha.downcase.include? "end of data") && @file_type == "mainframe"
            resultado = OriginField.text_parser(@file_type, linha, @origin.id, current_user.id)
            if resultado
              conta_valido += 1
            end
          end
          conta_linha += 1
        end
      end

      if resultado || conta_valido > 0
        redirect_to @origin, notice: "#{conta_valido} #{OriginField.model_name.human.capitalize} criados com sucesso"
      else
        redirect_to @origin, notice: "Nenhum #{OriginField.model_name.human.capitalize} foi criado!"
      end
    end
  end

  private

  def set_desabled_fields
    if @current_user.room1?
      @disabled_for_room1 = "false"
    else
      @disabled_for_room1 = "true"
    end

    if @current_user.room2?
      @disabled_for_room2 = "false"
    else
      @disabled_for_room2 = "true"
    end
  end

  def set_origin
    @origin = Origin.find(params[:id])
  end

  def origin_params
    params.require(:origin).permit(
      :file_name,
      :file_description,
      :created_in_sprint,
      :updated_in_sprint,
      :abbreviation,
      :base_type,
      :book_mainframe,
      :periodicity,
      :periodicity_details,
      :data_retention_type,
      :extractor_file_type,
      :room_1_notes,
      :mnemonic,
      :cd5_portal_origin_code,
      :cd5_portal_origin_name,
      :cd5_portal_destination_code,
      :cd5_portal_destination_name,
      :hive_table_name,
      :mainframe_storage_type,
      :room_2_notes,
      :dmt_advice,
      :dmt_classification,
      :status
    ).merge(current_user_id: current_user.id)
  end

  def set_origin_field
    @origin_field = OriginField.find(params[:id])
  end

  def set_query_param
    @text_param   = Origin.arel_table[:file_name].matches("%#{params[:text_param]}%").to_sql
    @status_param = Origin.arel_table[:status].matches("%#{params[:status_param]}%").to_sql
  end

  def origin_field_params
    params.require(:origin_field).permit(
      :field_name,
      :origin_pic,
      :data_type,
      :fmbase_format_type,
      :generic_data_type,
      :decimal,
      :mask,
      :position,
      :width,
      :is_key,
      :will_use,
      :has_signal,
      :room_1_notes,
      :cd5_variable_number,
      :cd5_output_order,
      :cd5_variable_name,
      :cd5_origin_format,
      :cd5_origin_format_desc,
      :cd5_format,
      :cd5_format_desc,
      :default_value,
      :room_2_notes,
      :domain,
      :dmt_notes,
      :fmbase_format_datyp,
      :generic_datyp,
      :cd5_origin_frmt_datyp,
      :cd5_frmt_origin_desc_datyp,
      :default_value_datyp,
      :origin_id
    ).merge(current_user_id: current_user.id)
  end
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/views/origins/_origin_details.html.erb
<section>
  <h3 class="line-bottom">Cadastro de <%= this_model_name( Origin ) %></h3>

  <h2><%= @current_user.profile %></h2>
  <div class="box-info">
    <table class="resumo">
      <tbody>
       <% if @current_user.room1? %>
         <tr>
           <th><%= t('activerecord.attributes.origin.file_name') %>:</th>
           <td><%= @origin.file_name %></td>
         </tr>
         <tr>
          <th><%= t('activerecord.attributes.origin.file_description') %>:</th>
          <td><%= @origin.file_description %></td>
         </tr>
       <% end %>
       <% if @current_user.room2? %>
         <tr>
           <th><%= t('activerecord.attributes.origin.mnemonic') %>:</th>
           <td><%= @origin.mnemonic %></td>
         </tr>
         <tr>
           <th><%= t('activerecord.attributes.origin.file_description') %>:</th>
           <td><%= @origin.file_description %></td>
         </tr>
         <tr>
           <th><%= t('activerecord.attributes.origin.hive_table_name') %>:</th>
           <td><%= @origin.hive_table_name %></td>
         </tr>
         <tr>
           <th><%= t('activerecord.attributes.origin.mainframe_storage_type') %>:</th>
           <td><%= @origin.mainframe_storage_type %></td>
         </tr>
         <tr>
           <th><%= t('activerecord.attributes.origin.room_2_notes') %>:</th>
           <td><%= @origin.room_2_notes %></td>
         </tr>
       <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/origins/_origin_fields_form.html.erb
<a name="forms-construido" class="link-ancora"></a>
<section>
<h3 class="line-bottom">Adicionar <span class="destaque"><%= this_model_name(OriginField) %> </span></h3>

  <%= form_for :origin_field, url: create_or_update_origin_field_path do |f| %>
    <% if @origin_field.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@origin_field.errors.count, "error") %> proibiram esse campo de origem de ser salvo:</h2>
        <ul>
          <% @origin_field.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset>

      <legend></legend>

      <div class="row clearfix">
        <div class="left t7">
          <%= f.label :field_name %>
          <%= f.text_field :field_name, disabled: !@current_user.room1? %>
        </div>
        <div class="left t10">
          <%= f.label :origin_pic %>
          <%= f.text_field :origin_pic, disabled: !@current_user.room1? %>
        </div>
        <div class="left t8">
          <%= f.label :data_type %>
          <%= f.select(:data_type, Constants::DATA_TYPES, {:include_blank => 'Selecione'}, disabled: !@current_user.room1?) %>
        </div>
        <div class="left t9">
          <%= f.label :fmbase_format_type %>
          <%= f.select(:fmbase_format_type, Constants::FMBASE_FORMAT_TYPE, {:include_blank => 'Selecione'}, disabled: true) %>
        </div>
        <div class="left t9">
          <%= f.label :generic_data_type %>
          <%= f.select(:generic_data_type, Constants::GENERIC_DATA_TYPE, {:include_blank => 'Selecione'}, disabled: true) %>
        </div>
      </div>

      <div class="row clearfix">
        <div class="left t10">
          <%= f.label :decimal %>
          <%= f.text_field :decimal, disabled: !@current_user.room1?  %>
        </div>
        <div class="left t10">
          <%= f.label :mask %>
          <%= f.text_field :mask, disabled: !@current_user.room1?  %>
        </div>
      </div>

      <div class="row clearfix">
        <div class="left t10">
          <%= f.label :position %>
          <%= f.text_field :position, disabled: !@current_user.room1?  %>
        </div>
        <div class="left t10">
          <%= f.label :width %>
          <%= f.text_field :width, disabled: !@current_user.room1?  %>
        </div>
        <div class="left t10">
          <%= f.label :is_key %>
          <%= f.select(:is_key, Constants::YES_NO, {:include_blank => 'Selecione'}, disabled: !@current_user.room1? ) %>
        </div>
         <div class="left t8">
          <%= f.label :will_use %>
          <%= f.select(:will_use, Constants::YES_NO, {:include_blank => 'Selecione'}, disabled: !@current_user.room1? ) %>
        </div>
         <div class="left t10">
          <%= f.label :has_signal %>
          <%= f.select(:has_signal, Constants::YES_NO, {:include_blank => 'Selecione'}, disabled: !@current_user.room1? ) %>
        </div>
      </div>

      <div class="row clearfix">
        <div class="left t6">
          <%= f.label :room_1_notes %>
          <%= f.text_area :room_1_notes, rows: 5, disabled: !@current_user.room1?   %>
        </div>
        <div class="left t6">
          <%= f.label :domain %>
          <%= f.text_area :domain, rows: 5, disabled: !@current_user.room1?   %>
        </div>
        <div class="left t6">
          <%= f.label :dmt_notes %>
          <%= f.text_area :dmt_notes, rows: 5, disabled: !@current_user.room1?  %>
        </div>
     </div>

      <div class="row clearfix">
        <div class="left t6">
          <%= f.label :cd5_variable_number %>
          <%= f.text_field :cd5_variable_number, :size=>"5", disabled: @current_user.room1?   %>
        </div>
        <div class="left t6">
          <%= f.label :cd5_output_order %>
          <%= f.text_field :cd5_output_order, :size=>"5", disabled: @current_user.room1?   %>
        </div>
      </div>

      <div class="row clearfix">
        <div class="left t6">
          <%= f.label :cd5_variable_name %>
          <%= f.text_field :cd5_variable_name, disabled: @current_user.room1?  %>
        </div>
        <div class="left t6">
          <%= f.label :cd5_origin_format %>
          <%= f.select(:cd5_origin_format, Constants::CD5_ORIGIN_FORMAT, {:include_blank => 'Selecione'}, disabled: @current_user.room1?) %>
        </div>
        <div class="left t6">
          <%= f.label :cd5_origin_format_desc %>
          <%= f.select(:cd5_origin_format_desc, Constants::CD5_ORIGIN_FORMAT_DESC, {:include_blank => 'Selecione'}, disabled: @current_user.room1?) %>
        </div>
      </div>

      <div class="row clearfix">
        <div class="left t6">
          <%= f.label :cd5_format %>
          <%= f.text_field :cd5_format, disabled: @current_user.room1?  %>
        </div>
        <div class="left t6">
          <%= f.label :cd5_format_desc %>
          <%= f.text_field :cd5_format_desc, disabled: @current_user.room1?  %>
        </div>
        <div class="left t6">
          <%= f.label :default_value %>
          <%= f.text_field :default_value, disabled: @current_user.room1?  %>
        </div>
      </div>


      <div class="row clearfix">
        <div class="left t6">
          <%= f.label :room_2_notes %>
          <%= f.text_area :room_2_notes, rows: 5, disabled: @current_user.room1?   %>
        </div>
      </div>

      <div class="row clearfix">
        <div class="left t6">
          <%= f.label :fmbase_format_datyp %>
          <%= f.text_field :fmbase_format_datyp, :size=>"5", :disabled => true  %>
        </div>
        <div class="left t6">
          <%= f.label :generic_datyp %>
          <%= f.text_field :generic_datyp, :size=>"5", :disabled => true  %>
        </div>
        <div class="left t6">
          <%= f.label :cd5_origin_frmt_datyp %>
          <%= f.text_field :cd5_origin_frmt_datyp, :size=>"5", :disabled => true  %>
        </div>
      </div>

      <div class="row clearfix">
        <div class="left t6">
          <%= f.label :cd5_frmt_origin_desc_datyp %>
          <%= f.text_field :cd5_frmt_origin_desc_datyp, :size=>"5", :disabled => true  %>
        </div>
        <div class="left t6">
          <%= f.label :default_value_datyp %>
          <%= f.text_field :default_value_datyp, :size=>"5", :disabled => true  %>
        </div>
      </div>

    </fieldset>

    <div class="actions">
      <%= f.submit "Salvar #{OriginField.model_name.human.capitalize}" %>
    </div>

    <%= f.hidden_field :origin_id, value: @origin.id %>
    <%= f.hidden_field :origin_field_id, value: @origin_field.id %>

  <% end %>

</section>

app/views/origins/_origin_fields_index.html.erb
<section>
  <h3 class="line-bottom">Cadastro de <span class="destaque"><%= this_model_name(OriginField) %></h3>

  <table summary="" class="tabela-zebra tabela-hover">
    <thead>
      <tr>
        <th><%= t('activerecord.attributes.origin_field.field_name') %></th>
        <th><%= t('activerecord.attributes.origin_field.origin_pic') %></th>
        <th><%= t('activerecord.attributes.origin_field.data_type') %></th>
        <th><%= t('activerecord.attributes.origin_field.decimal') %></th>
        <th><%= t('activerecord.attributes.origin_field.mask') %></th>
        <th><%= t('activerecord.attributes.origin_field.position') %></th>
        <th><%= t('activerecord.attributes.origin_field.width') %></th>
        <th><%= t('activerecord.attributes.origin_field.is_key')  %></th>
        <th><%= t('activerecord.attributes.origin_field.will_use')  %></th>
        <th><%= t('activerecord.attributes.origin_field.has_signal') %></th>

        <% if @current_user.room2?%>
          <th><%= t('activerecord.attributes.origin_field.cd5_variable_number') %></th>
          <th><%= t('activerecord.attributes.origin_field.cd5_output_order') %></th>
        <% end %>
        <th></th>

        <% if @current_user.room1?%>
          <td></td>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @origin.origin_fields.each do |origin_field| %>
        <tr>
          <td><%= link_to origin_field.field_name.to_s, get_origin_field_to_update_path(id: origin_field.id) %></td>
          <td><%= origin_field.origin_pic %></td>
          <td><%= origin_field.data_type %></td>
          <td><%= origin_field.decimal %></td>
          <td><%= origin_field.mask %></td>
          <td><%= origin_field.position %></td>
          <td><%= origin_field.width %></td>
          <td><%= boolean_to_sim_nao(origin_field.is_key) %></td>
          <td><%= boolean_to_sim_nao(origin_field.will_use) %></td>
          <td><%= boolean_to_sim_nao(origin_field.has_signal) %></td>

          <% if @current_user.room2? %>
            <td><%= origin_field.cd5_variable_number %></td>
            <td><%= origin_field.cd5_output_order %></td>
          <% end %>

          <td><%= link_to t('edit'), get_origin_field_to_update_path(id: origin_field.id) %></td>

          <% if @current_user.room1? %>
            <td><%= link_to t('destroy'), destroy_origin_field_path(origin_field.id), method: :delete, data: { confirm: t('are_you_sure') } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/origins/_room1_form_upload.html.erb
<a name="forms-construido" class="link-ancora"></a>
<section>
  <h3 class="line-bottom">Adicionar <span class="destaque"><%= this_model_name(OriginField) %> através de upload</span></h3>
  <%= form_for :origin_field, url: create_origin_field_upload_path, :multipart => true do |f| %>
    <fieldset>
      <legend></legend>
      <div class="row clearfix">
        <%= f.hidden_field :origin_id, value: @origin.id %>
        <div class="left t6">
          <p class="left"><%= radio_button_tag 'file_type', "mainframe", checked: true %> Mainframe</p>
        </div>
        <div class="left t6">
          <p class="left"><%= radio_button_tag 'file_type', "hadoop" %> Hadoop</p>
        </div>
      </div>
    </fieldset>
    <div class="row clearfix">
      <div class="actions">
        <label for="upload_file">Selecione o Arquivo</label>
        <%= f.file_field 'datafile' %>
      </div>
    </div>
    <div class="row clearfix">
      <div class="actions">
        <%= submit_tag "Upload" %>
      </div>
    </div>
  <% end %>
</section>

app/views/origins/edit.html.erb
<%= render 'room1_form' if @current_user.room1? %>
<%= render 'room2_form' if @current_user.room2? %>

app/views/origins/index.html.erb
<section class="main">
  <div class="row clearfix">
    <div class="col13" role="main">
      <div class="modulo">
        <section class="formulario">
          <h3 class="line-bottom">Origens</h3>
          <fieldset>
            <legend></legend>
            <%= form_tag(search_origin_path,  method: :get ) do  %>
              <div class="row clearfix">
                <div class='left t4'>
                  <%= text_field_tag 'text_param', params[:text_param] || '' %>
                </div>
                <div class="left t10">
                  <label class="custom-select"><%= select_tag "status_param", options_for_select(Constants::STATUS, params[:status_param] || nil), prompt: 'Todos' %></label>
                </div>
                <div class="left btn btn-primary">
                  <%= submit_tag "Filtrar" %>
                </div>
              </div>
            <% end %>
          </fieldset>
          <section>
            <table summary="" class="tabela-zebra tabela-hover">
              <thead>
                <tr class="txt-no-transform">
                  <th>arquivo / base</th>
                  <th>sprint criado</td>
                  <th>sprint alterado</td>
                  <th>sigla</td>
                  <th>tipo</td>
                  <th>periodicidade</td>
                  <th>mnemônico</td>
                  <th>cód origem CD5</td>
                  <th>cód destino CD5</td>
                  <th>status</td>
                </tr>
              </thead>
              <tbody>
                <% @origins.each do |origin| %>
                  <tr>
                    <td><%= origin.file_name %></td>
                    <td><%= origin.created_in_sprint %></td>
                    <td><%= origin.updated_in_sprint %></td>
                    <td><%= origin.abbreviation %></td>
                    <td><%= origin.base_type %></td>
                    <td><%= origin.periodicity %></td>
                    <td><%= origin.mnemonic %></td>
                    <td><%= origin.cd5_portal_origin_code %></td>
                    <td><%= origin.cd5_portal_destination_code %></td>
                    <td><%= origin.status %></td>
                    <td><%= link_to t('edit'), edit_origin_path(origin) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table> <!-- summary="" class="tabela-zebra tabela-hover" -->
            <div>
              <%= will_paginate @origins %>
            </div>
          </section> <!-- grid section -->
        </section> <!-- formulario -->
      </div> <!-- modulo -->
    </div> <!-- col -->
  </div> <!-- row clearfix -->
</section> <!-- main -->

app/views/origins/new.html.erb
<h1>Nova <%= Origin.model_name.human.capitalize %></h1>

<% if @current_user.room1? %>
  <%= render 'room1_form' %>
<% end %>

<% if @current_user.room2? %>
  <%= render 'room2_form' %>
<% end %>

app/views/origins/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'origin_details' %>
<%= render 'origin_fields_index' %>
<%= render 'room1_form_upload' %>
<%= render 'origin_fields_form' %>