config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, :origins, :origin_fields, :processids, :tables, :campaigns, :variables


  post "index" => "welcome#index"
  get  "index" => "welcome#index"

  post "/create_or_update_origin_field" => "origins#create_or_update_origin_field"
  get "/get_origin_field_to_update"     => "origins#get_origin_field_to_update"
  delete "/destroy_origin_field"        => "origins#destroy_origin_field"

  post "/create_origin_field_upload" => "origins#create_origin_field_upload"

  match '/export_script', to: 'scripts#index', via: [:get, :post]

  match 'variable_name_search'               , to: 'variables#name_search'          , :via => :get
  match 'campaign_variables_search/(:id)'    , to: 'campaigns#variables_search'     , :via => :get
  match 'table_variables_search/(:id)'       , to: 'tables#variables_search'        , :via => :get
  match 'processid_variables_search/(:id)'   , to: 'processids#variables_search'    , :via => :get
  match 'origin_field_name_search'           , to: 'origins#name_search'            , :via => :get
  match 'variable_origin_fields_search/(:id)', to: 'variables#origin_fields_search' , :via => :get

  get "user/index"
  get "/login"             => "users#login"
  post "/signin"           => "users#authenticate"
  get  "/signup"           => "users#new"
  get  "/logout"           => "users#logout"
  get  "/password"         => "users#password"
  post "/password_update"  => "users#password_update"

  get  "/remember_password/:id" => "users#remember_password_index", :as => "remember"
  post "/remember_password"     => "users#remember_password"

  get "/search/origin"    => "origins#search",    :as => "search_origin"
  get "/search/campaign"  => "campaigns#search",  :as => "search_campaign"
  get "/search/table"     => "tables#search",     :as => "search_table"
  get "/search/processid" => "processids#search", :as => "search_processid"
  get "/search/variable"  => "variables#search",  :as => "search_variable"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @filter = params[:status] || 'origin'

    @items = case @filter
             when "origin"
               [Origin.select(:id, :status, :file_name).draft.recent.limit(10),
                Origin.select(:id, :status, :file_name).development.recent.limit(10),
                Origin.select(:id, :status, :file_name).done.recent.limit(10)]
             when "campaign"
               [Campaign.select(:id, :status, :name).draft.recent.limit(10),
                Campaign.select(:id, :status, :name).development.recent.limit(10),
                Campaign.select(:id, :status, :name).done.recent.limit(10)]
             when "variable"
               [Variable.select(:id, :status, :name).draft.recent.limit(10),
                Variable.select(:id, :status, :name).development.recent.limit(10),
                Variable.select(:id, :status, :name).done.recent.limit(10)]
             when "table"
               [Table.select(:id, :status, :logic_table_name).draft.recent.limit(10),
                Table.select(:id, :status, :logic_table_name).development.recent.limit(10),
                Table.select(:id, :status, :logic_table_name).done.recent.limit(10)]
             when "processid"
               [Processid.select(:id, :status, :mnemonic).draft.recent.limit(10),
                Processid.select(:id, :status, :mnemonic).development.recent.limit(10),
                Processid.select(:id, :status, :mnemonic).done.recent.limit(10)]
             end

    @max_size = [@items[0].size, @items[1].size, @items[2].size].max
  end
end

app/views/welcome/index.html.erb
<section class="main">
  <div class="row clearfix">
    <div class="col2" role="complementary">
      <div class="modulo modulo-sidebar" id="guide-move">
        <h4>Cadastros</h4>
        <div class="botoes clearfix">
          <% if @current_user.room1? %>
            <div class="row clearfix">
              <%= link_to capitalized_name(Origin),   new_origin_path,   id: "new_origin",   :class => "btn btn-secundario left txt-no-transform" %>
            </div>
            <div class="row clearfix">
              <%= link_to capitalized_name(Campaign), new_campaign_path, id: "new_campaign", :class => "btn btn-secundario left txt-no-transform" %>
            </div>
            <div class="row clearfix">
              <%= link_to capitalized_name(Variable), new_variable_path, id: "new_variable", :class => "btn btn-secundario left txt-no-transform" %>
            </div>
            <div class="row clearfix">
              <%= link_to capitalized_name(Table),    new_table_path,    id: "new_table",    :class => "btn btn-secundario left txt-no-transform" %>
            </div>
          <% end %>

          <% if @current_user.room2? %>
            <div class="row clearfix">
              <%= link_to capitalized_name(Processid), new_processid_path, id: "new_processid", :class => "btn btn-secundario left txt-no-transform" %>
            </div>
          <% end %>

        </div>
      </div>

      <% if @current_user.room2? %>
        <div class="modulo modulo-sidebar" id="guide-move">
          <h4>Utilitários</h4>
          <div class="botoes clearfix">
            <div class="row clearfix">
              <%= link_to "Exportar", export_script_path, id: "export", :class => "btn btn-secundario left txt-no-transform" %>
            </div>
          </div>
        </div>
      <% end %>
    </div> <!-- div class=col2 -->

    <div class="col10" role="main">
      <div class="modulo">
        <section class="formulario">
          <h3 class="line-bottom">Status</h3>
          <fieldset>
            <legend></legend>
            <div id="status" class="row clearfix line-bottom">
              <%= form_tag( index_path ) do  %>
                <p class="left">
                  <input type="radio" value="origin" <%='checked' if @filter == 'origin' %> id="status01" name="status", onclick="this.form.submit();" />
                  <label for="status01"><%= this_model_name( Origin ) %></label>
                </p>

                <% if @current_user.room1? %>
                  <p class="left">
                    <input type="radio" value="campaign" <%='checked' if @filter == 'campaign' %> id="status02" name="status", onclick="this.form.submit();" />
                    <label for="status02"><%= this_model_name( Campaign ) %></label>
                  </p>
                <% end %>

                <p class="left">
                  <input type="radio" value="variable" <%='checked' if @filter == 'variable' %> id="status03" name="status", onclick="this.form.submit();" />
                  <label for="status03"><%= this_model_name( Variable ) %></label>
                </p>

                <% if @current_user.room2? %>
                  <p class="left">
                    <input type="radio" value="processid" <%='checked' if @filter == 'processid' %> id="status05" name="status", onclick="this.form.submit();" />
                    <label for="status05"><%= this_model_name( Processid ) %></label>
                  </p>
                <% end %>

                <p class="left">
                  <input type="radio" value="table" <%='checked' if @filter == 'table' %> id="status04" name="status", onclick="this.form.submit();" />
                  <label for="status04"><%= this_model_name( Table ) %></label>
                </p>
              <% end %>
            </div> <!-- row clearfix -->
          </fieldset>

          <section>
            <table summary="" class="tabela-zebra tabela-hover">
              <thead>
                <tr class="txt-no-transform">
                  <th>SALA1</th>
                  <th>SALA2</th>
                  <th>PRODUÇÃO</th>
                </tr>
              </thead>
              <tbody>
                <% if @items.empty? %>
                  <tr>
                    <td class="largura-fixa120"></td>
                    <td class="largura-fixa120"></td>
                    <td class="largura-fixa120"></td>
                  </tr>
                <% else %>
                  <% 0.upto(@max_size - 1) do |i| %>
                    <tr>
                      <% 3.times do |column| %>
                        <td class="largura-fixa120">
                          <%= link_to "#{@items[column][i].code} #{@items[column][i].status_screen_name}", "#{@filter}s/#{@items[column][i].id}/edit" unless @items[column][i].nil? %>
                        </td>
                      <% end %>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table> <!-- summary="" class="tabela-zebra tabela-hover" -->

            <% if @max_size > 0 %>
              <div>
                <%= link_to "mais ...", entity_path %>
              </div>
            <% end %>

          </section> <!-- grid section -->
        </section> <!-- formulario -->
      </div> <!-- modulo -->
    </div> <!-- col -->
  </div> <!-- row clearfix -->
</section> <!-- main -->