config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, :origins, :origin_fields, :processids, :tables, :campaigns, :variables


  post "index" => "welcome#index"
  get  "index" => "welcome#index"

  post "/create_or_update_origin_field" => "origins#create_or_update_origin_field"
  get "/get_origin_field_to_update"     => "origins#get_origin_field_to_update"
  delete "/destroy_origin_field"        => "origins#destroy_origin_field"

  post "/create_origin_field_upload" => "origins#create_origin_field_upload"

  match '/export_script', to: 'scripts#index', via: [:get, :post]

  match 'variable_name_search'               , to: 'variables#name_search'          , :via => :get
  match 'campaign_variables_search/(:id)'    , to: 'campaigns#variables_search'     , :via => :get
  match 'table_variables_search/(:id)'       , to: 'tables#variables_search'        , :via => :get
  match 'processid_variables_search/(:id)'   , to: 'processids#variables_search'    , :via => :get
  match 'origin_field_name_search'           , to: 'origins#name_search'            , :via => :get
  match 'variable_origin_fields_search/(:id)', to: 'variables#origin_fields_search' , :via => :get

  get "user/index"
  get "/login"             => "users#login"
  post "/signin"           => "users#authenticate"
  get  "/signup"           => "users#new"
  get  "/logout"           => "users#logout"
  get  "/password"         => "users#password"
  post "/password_update"  => "users#password_update"

  get  "/remember_password/:id" => "users#remember_password_index", :as => "remember"
  post "/remember_password"     => "users#remember_password"

  get "/search/origin"    => "origins#search",    :as => "search_origin"
  get "/search/campaign"  => "campaigns#search",  :as => "search_campaign"
  get "/search/table"     => "tables#search",     :as => "search_table"
  get "/search/processid" => "processids#search", :as => "search_processid"
  get "/search/variable"  => "variables#search",  :as => "search_variable"
end

app/views/layouts/_content.html.erb
<section class="container clearfix">
  <section class="alerta">
  </section>
  <div id="content">
    <%= yield %>
  </div>
</section>
<!-- end Conteúdo Principal -->

app/views/layouts/_footer.html.erb
<footer class="clearfix">
  <section class="container" role="contentinfo">
    PORTAL DE VARIAVEIS
  </section>
</footer>

app/views/layouts/_header_30h.html.erb
<div class="ico-30h right">
  <img src=<%= asset_path("ico-30h-medio.png")%> alt="Ícone 30 horas" />
</div>

app/views/layouts/_header_ico_config_left.html.erb
<div class="ico-configuracoes right">
  <%= link_to( users_path ) do  %>
    <span class="ico-config"></span>
  <% end %>
</div>

app/views/layouts/_header_menu.html.erb
<!-- start Header e Menu -->
<a name="top" class="link-ancora"></a>
<header class="clearfix">
  <section class="container">
    <section class="content-main header" role="banner">
      <div class="logo left"><img src=<%= asset_path("logo-itau-mini.png")%> alt="Logo Itaú" /></div>
      <%= render 'layouts/header_menu_busca' %>
      <% if @current_user %>
        <%= render 'layouts/header_sair' %>
        <%= render 'layouts/header_ico_config_left' %>
        <%= render 'layouts/header_menu_dados_usuarios' %>
        <!-- %= render 'layouts/header_30h' % -->
      <% end %>
    </section> <!-- containt main reader -->
    <nav class="menu" role="navigation">
      <ul class="itens">
        <%= content_tag :li, link_to('Home', root_path),  class: "mnu" %>
      </ul>
    </nav>
  </section><!-- container -->
</header>
<!-- end Header e Menu -->

app/views/layouts/_header_menu_busca.html.erb
<div class="dados-usuario left">
  <p class="nome">
    >>> PORTAL DE
    <span class="destaque">
    VARIAVEIS
    </span> 
  </p>
</div>

app/views/layouts/_header_menu_dados_usuarios.html.erb
<div class="dados-usuario data-placement=right right">
  <p class="nome">
  Olá <%= link_to @current_user.name, edit_user_path(@current_user) %> - <%= @current_user.profile %>
  </p>
</div>

app/views/layouts/_header_sair.html.erb
<div class="btn-sair right">
  <%= link_to( logout_path, :class => "btn btn-fluxo btn-ico" ) do  %>
    Sair
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br" class="no-js">
  <head>
    <meta charset="utf-8" />
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <![endif]-->
    <title>Portal de Variáveis - Itaú</title>
    <meta name="robots" content="noindex,nofollow" />
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body> <!-- Para trocar o segmento, basta inserir um ID identificador. Ex: id="person" -->

    <!-- start Header e Menu -->
    <%= render 'layouts/header_menu' %>
    <!-- end Header e Menu -->

    <!-- start Conteúdo Principal -->
    <%= render 'layouts/content' %>
    <!-- end Conteúdo Principal -->

    <!-- start Footer -->
    <%= render 'layouts/footer' %>
    <!-- end Footer -->

    <!-- JS -->
    <%= javascript_include_tag :select2 %>
    <!-- JS -->

  </body>
</html>